name: '[FAZ] TF - Standalone'

env:
  TFPath: FortiAnalyzer/terraform/
  ZIPfile: FortiAnalyzer_Standalone_Terraform.zip

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'FortiAnalyzer/terraform/*.tf'
      - 'FortiAnalyzer/terraform/*.tpl'
      - 'FortiAnalyzer/terraform/*.hcl'
      - 'FortiAnalyzer/terraform/*.json'
      - 'FortiAnalyzer/terraform/*.yaml'

jobs:
  OCI-FGT-TF-Standalone:
    name: 'Terraform FortiAnalyzer Standalone'
    runs-on: ubuntu-latest
    env:
      TF_VAR_tenancy_ocid: "${{ secrets.TENANCY_OCID }}"
      TF_VAR_compartment_ocid: "${{ secrets.COMPARTMENT_OCID }}"
      TF_VAR_user_ocid: "${{ secrets.USER_OCID }}"
      TF_VAR_region: "${{ secrets.REGION }}"
      TF_VAR_fingerprint: "${{ secrets.FINGERPRINT }}"
      TF_VAR_private_key_path: ~/.oci/oci_api_key.pem
      TF_VAR_igw_ocid: "${{ secrets.IGW_OCID }}"
      TF_VAR_vcn_ocid: "${{ secrets.VCN_OCID }}"
      TF_VAR_vcn_cidr: "${{ secrets.VCN_CIDR }}"
      TF_VAR_availability_domain_name_1: "${{ secrets.AVAILABILITY_DOMAIN_NAME_1 }}"
      TF_VAR_cpu_type: "${{ secrets.CPU_TYPE }}"
      TF_VAR_fortios_version: "${{ secrets.FORTIOS_VERSION }}"
      TF_VAR_license_type: "${{ secrets.LICENSE_TYPE }}"
      TF_VAR_vm_compute_shape: "${{ secrets.VM_COMPUTE_SHAPE }}"
      TF_VAR_compute_compartment_ocid: "${{ secrets.COMPUTE_COMPARTMENT_OCID }}"
      
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Setup Terraform"
      uses: hashicorp/setup-terraform@v3

    - name: Configure OCI credentials
      run: |
        mkdir -p ~/.oci
        echo "${{ secrets.OCI_PEM_KEY }}" > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem

    - name: "Terraform Init"
      id: init
      run: terraform init
      working-directory: ${{ env.TFPath }}

    - name: "Terraform Validation"
      id: validate
      run: terraform validate
      working-directory: ${{ env.TFPath }}

    - name: "Terraform Format"
      id: format
      run: terraform fmt -check -diff
      working-directory: ${{ env.TFPath }}

    - name: "Terraform Plan"
      id: plan
      run: terraform plan -out plan.tfplan
      working-directory: ${{ env.TFPath }}

    - name: "Terraform Show"
      id: show
      run: terraform show -json plan.tfplan
      working-directory: ${{ env.TFPath }}

    - name: "Save Plan JSON"
      run: echo '${{ steps.show.outputs.stdout }}' > plan.json # Do not change

    - name: Package and convert templates
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Compress-Archive -Path "./FortiAnalyzer/*" -DestinationPath "./${{ env.ZIPfile }}"
        azPSVersion: "latest"

    - name: upload-templates-zip
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        file: ./${{ env.ZIPfile }}
        asset_name: ${{ env.ZIPfile }}
        tag: fazstandalone
        overwrite: true
        body: "OCI FortiAnalyzer Standalone"
