name: '[FGT] OCI - DRGv2 Hub Spoke trafic inspection'

env:
  ARMPath: FortiGate/DRGv2-HubSpoke/

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - 'FortiGate/DRGv2-HubSpoke/*.tf'

jobs:
  OCI-DRGv2-Hub-Spoke:
    name: 'OCI Terraform template DRGv2 Hub Spoke'
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: Package and convert templates
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Compress-Archive -Path "./FortiGate/DRGv2-HubSpoke/*" -DestinationPath "./terraform-drgv2-hubspoke.zip"
        azPSVersion: "latest"

    - name: upload-templates-zip
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        file: ./terraform-drgv2-hubspoke.zip
        asset_name: terraform-drgv2-hubspoke.zip
        tag: ${{github.ref}}
        overwrite: true
        body: "OCI FortiGate DRGv2 Hub Spoke"