name: Generate Final Listings JSON

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight UTC on the 1st of every month
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  generate-json:
    runs-on: ubuntu-latest
    env:
      TFPath: FortiAnalyzer/terraform/

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Needed for pushing changes

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install OCI SDK
      run: pip install oci

    - name: Configure OCI credentials
      run: |
        mkdir -p ~/.oci
        echo "${{ secrets.OCI_PEM_KEY }}" > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem

    - name: Run Python script to generate JSON
      env:
        USER_OCID: ${{ secrets.USER_OCID }}
        FINGERPRINT: ${{ secrets.FINGERPRINT }}
        TENANCY_OCID: ${{ secrets.TENANCY_OCID }}
        REGION: ${{ secrets.REGION }}
      run: |
        python .github/workflows/scripts/ocimarketplace.py  # Adjust path if ocimarketplace.py is not at root

    - name: Copy final_listings.json to all product folders
      run: |
        # Copy generated JSON file to each folder
        cp final_listings.json FortiAnalyzer/terraform/
        cp final_listings.json FortiManager/terraform/
        cp final_listings.json FortiGate/Standalone/terraform/
        cp final_listings.json FortiGate/Active-Passive/terraform/

    - name: Commit and push updated JSON files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add FortiAnalyzer/terraform/final_listings.json
        git add FortiManager/terraform/final_listings.json
        git add FortiGate/Standalone/terraform/final_listings.json
        git add FortiGate/Active-Passive/terraform/final_listings.json
        git commit -m "Automated update of final_listings.json on 1st of month" || echo "No changes to commit"
        git push
